name: breweries_case

services:
  airflow:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    container_name: airflow
    entrypoint: ["bash", "/entrypoint.sh"]
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow/src
    ports:
      - "8080:8080"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
    networks:
      - default

networks:
  default:
    name: breweries_case_default
